### ISSUE TITLE
Open source the mobile app repo

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/HyloReactNative#353]
Have done an initial audit and not came-up with anything that should hold this back with one possible small exception which needs a brief looking into:

* `ios/sentry.properties` and `android/sentry.properties`

This token can likely be put in an environment variable and the properties files generated in the `scripts/configure.sh` script we're using for similar files and values.

*Other than getting us one step closer to open contribution, this also will enable the GitHub "draft" Pull Request feature which is not otherwise an option on our private repositories. That's a nice-to-have, but certainly not a big thing.*

Ref https://m25lazi.medium.com/environment-variables-in-xcode-a78e07d223ed for how to move keys in iOS code into a local `.xcode_env`

**Comment by lorenjohnson** [comment]
Done!

**Comment by tibetsprague** [comment]
🙌
